version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test-and-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - add_ssh_keys:
          fingerprints:
            - "c5:cc:ca:66:b6:a2:57:85:c9:e1:05:fd:52:8d:b7:82"
      - run:
          name: 'Setup'
          command: |
            ssh-keyscan -p 2222 $SERVER_IP >> ~/.ssh/known_hosts
            ssh circleci@$SERVER_IP -p 2222 'ls -la'

workflows:
  deploy:
    jobs:
      - test-and-deploy
