version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - add_ssh_keys:
                fingerprints:
                  - '72:4b:04:64:64:74:16:41:21:96:27:22:c2:b2:8a:e0'
            - run: ssh circleci@showme.aurer.dev -p 2222 'sh update-showme.sh'
workflows:
  build-and-test:
    jobs:
      - build-and-test
