version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - add_ssh_keys:
                fingerprints:
                  - 'fb:b7:99:5d:89:ae:ff:2e:ea:4f:61:ff:09:fd:f2:99'
            - run: ssh circleci@showme.aurer.dev -p 2222 'sh update-showme.sh'
workflows:
  build-and-test:
    jobs:
      - build-and-test
