version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: ssh circleci@showme.aurer.dev 'sh update-showme.sh'
workflows:
  build-and-test:
    jobs:
      - build-and-test
